# This is a basic workflow to help you get started with Actions

name: CI

on:
    repository_dispatch:
      types: [test_result]
      branches:
      - master
      - terraform_test

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: test

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        env:
          BRANCH: ${{ github.event.client_payload.branch_ref }}
        with:
          fetch-depth: 0
          ref: ${{ github.event.client_payload.branch_ref }}

      - name: Run a one-line script
        env:
          BRANCH: ${{ github.event.client_payload.branch_ref }}
        run: echo $BRANCH; tail -5 Jenkinsfile
        
      # Runs a single command using the runners shell
      - name: print event 
        run: cat $GITHUB_EVENT_PATH

      - name: Run a one-line script
        run: echo Hello, world!!
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
