# This is a basic workflow to help you get started with Actions

name: CI 
run-name: Sandbox pipeline
on:
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  variables-definitions:
    # The type of runner that the job will run on
    runs-on: test
    steps:
      - name: Define variables
        id: vardef
        run: |
          printenv

          